### ISSUE TITLE
Triangle.gltf is not displayed

### ISSUE THREAD

**Issue by cx20** [shrekshao/minimal-gltf-loader#10]
I tried to display Triangle.gltf. However, there seems to be an error in the console.

[Triangle.gltf result](https://cdn.rawgit.com/cx20/gltf-test/a26f844c6fe2831c69c8b0e95f7b01f454f020c8/examples/minimal-gltf-loader/index.html?category=tutorialModels&model=Triangle&scale=1&type=glTF)
```js
index.js:256 
Uncaught TypeError: Cannot read property 'boundingBox' of undefined
    at MinimalGLTFLoader.glTFLoader.onload (index.js:256)
    at MinimalGLTFLoader.glTFLoader.glTFLoader._checkComplete (minimal-gltf-loader.js:697)
    at loadArrayBufferCallback (minimal-gltf-loader.js:935)
    at XMLHttpRequest.xobj.onreadystatechange (minimal-gltf-loader.js:1313)
```
Probably because there is no default scene in this model.
If default scene is not specified, it is a good idea to display the first scene.

**Comment by shrekshao** [comment]
@cx20 Great thanks for your constant help. I've fixed this at the latest HEAD, together with draw without instances. There's still an issue with animated triangle seems to be a known issue of the old loading code. 
As the loader features grow, the temp renderer becomes really ugly (and actually feature incomplete). I'm going to use this loader in one of my other project so that hopefully I can come back with a comparatively more robust and neat renderer (and also refactor some old code, and support for PBR). Might take some time to make the testing list all green. I hope that won't last for too long.

**Comment by cx20** [comment]
@shrekshao Thank you for fixing. The geometry is correct, but the color seems to be different than expected. Perhaps it is correct to gray as the default value.

[Minimal glTF Loader + Triangle.gltf result:](https://cx20.github.io/gltf-test/examples/minimal-gltf-loader/index.html?category=tutorialModels&model=Triangle&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/30116552-cd74c726-9358-11e7-8638-4f0a624e7279.png)

[Expected result:](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Triangle)
![image](https://user-images.githubusercontent.com/1833979/30116560-d2ce97f6-9358-11e7-877b-f6b93678e3e0.png)

**Comment by shrekshao** [comment]
@cx20 Hmm it seems to me the default material should be a plain white: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-material, https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-pbrmetallicroughness
Is it because I didn't implement PBR?

**Comment by cx20** [comment]
@shrekshao I'm sorry. Perhaps the specifications may be glTF 1.0 specifications.
https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#appendix-a-default-material
```
using a default material with 50% gray emissive color. 
```
@javagl Do you know what color Triangle.gltf (https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Triangle) is displayed correctly?

**Comment by javagl** [comment]
@cx20 The spec says that the the material in this case should be one where all values have their *default* values, as of https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#default-material 

So in that sense, the current screenshot (showing the dark gray triangle) could be considered to be "wrong", and the white one is more likely to be "correct" .... **assuming** that there is some sort of light. 

---

(Well, the gray one is still correct, *if* there only is a gray light ;-) Technically, every glTF renderer that shows a completely black screen for **every** model (at least, without `emissive` info) is a perfectly specification-compliant glTF renderer. As long as there are no lights, nothing is visible. So it's really hard to say what's "right" and "wrong" here...)

---

(Coincidentally, [one of the last changes in the 2.0 branch of JglTF](https://github.com/javagl/JglTF/commit/8971c5954617d2c6b44ebf65290720d7d3877770) was related exactly to that - namely, setting the proper "default material values". But it is still no complete. It will, in fact, be necessary to create a "Shader Generator", that generates the whole shader code based on the glTF material. Maybe I'll find some inspiration in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/master/lib/processModelMaterialsCommon.js , but this is also still incomplete...)

**Comment by cx20** [comment]
@javagl  I am a little surprised that white is correct. I thought that it was correct because the sample image and the execution results of [other libraries](https://github.com/cx20/gltf-test#simple-models-for-testing-individual-features) were gray. I would like to reconfirm the settings of the lights of other library samples.

**Comment by javagl** [comment]
@cx20 Some of the other renderers already have "proper PBR" - particularly, with environment-based lighting. You can see the *apparent* color change depending on the viewing angle, particularly in Three.js. 

But indeed, it's less visible in other viewers, and the differences are considerable.

There, the crucial questions are 1. which sort of lights they are using and 2. whether they are already using the default material of glTF 2.0. (For example, Cesium *might* still have the default material of 1.0 - but of course, without looking at the code, this is only a wild guess).

**Comment by cx20** [comment]
Since the triangle is already displayed, this Issue is closed.
As for writing, my understanding is insufficient, so if I find that it is a problem, I would like to report Issue again.
