### ISSUE TITLE
The light of the lantern.gltf does not light

### ISSUE THREAD

**Issue by cx20** [shrekshao/minimal-gltf-loader#11]
I tried to display [Lantern.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Lantern/glTF) with the latest Minimal glTF Loader.
However, The light of the lantern.gltf does not light.

[Three.js glTF Loader + Lantern.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/7c0922854c42440d57de3e0974daad7dd75ee574/examples/threejs/index.html?category=tutorialModels&model=Lantern&scale=0.06&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/30593691-76bac556-9d86-11e7-94ad-a6100974328f.png)

[Babylon.js glTF Loader + Lantern.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/7c0922854c42440d57de3e0974daad7dd75ee574/examples/babylonjs/index.html?category=tutorialModels&model=Lantern&scale=0.06&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/30593803-c9fbeb6e-9d86-11e7-801d-56f56fc36f4e.png)

[Minimal glTF loader + Lantern.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/7c0922854c42440d57de3e0974daad7dd75ee574/examples/minimal-gltf-loader/index.html?category=tutorialModels&model=Lantern&scale=0.06&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/30593901-1da95d28-9d87-11e7-8781-43811a7ed475.png)

Is it because [Lantern_emissive.png](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Lantern/glTF/Lantern_emissive.png) is not loaded?

**Comment by shrekshao** [comment]
Hi @cx20. Thanks for the report. 
It's because of the temporary implementation of PBR. I will inform you when I'm done with a full pbr example. Currently only model with occlusion, emissive, metallic, etc. everything will enable pbr rendering.
Just to let you know. I think the loader itself (not including the example renderer) should now support most features (excluding camera).

**Comment by cx20** [comment]
@shrekshao I understood that PBR implementation is WIP. If there is progress, I would like to test it again.

**Comment by shrekshao** [comment]
@cx20 Again thanks for your constant support and sorry about the trouble for letting you testing multiple times separately -_-

**Comment by shrekshao** [comment]
@cx20 I've fixed latern (moved everything to pbr shader) and draw without indices. Should fix Metal-Rough Spheres, Latern, and Triangle Without Indices. 
But I still haven't implemented TANGENT attribute. So I would suggest you update the test after I've finished with pretty much everything. I will let you know when I'm ready.
Thanks a lot!

**Comment by cx20** [comment]
I confirmed that several problems were solved. I think that PBR is almost perfect. 
(However, please be aware that I am an amateur about PBR.)
Therefore, I will close this Issue.
