### ISSUE TITLE
请教关于 skins 的疑问

### ISSUE THREAD

**Issue by PrincessGod** [shrekshao/minimal-gltf-loader#12]
狄学长，你好

我看到了你在[这里](https://www.bountysource.com/issues/48903423-computing-jointmatrix-of-skins-with-a-skeleton-node)提的问题，你现在有答案了么？我可能有一些想法。

我想看看你对glTF的`skinning`的实现，但是没找到相关代码，`README.md`中说明已经实现了`skin`，
所以我想问一下可否告诉我代码在哪？

谢谢。

**Comment by shrekshao** [comment]
他们把它标成了应该会在之后修改。我是没用到

相关runtime逻辑在index.js里，搜skin就行。

我是照着gltf repo readme那张图实现的

**Comment by PrincessGod** [comment]
看到了，你现在直接按照图片上的说法确定的根节点，谢谢。

对了，你对Cesium提出的[3D Tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles)有了解么？
我想做一个基于这个标准的空间模型batch工具，将多个独立的glTF合并为一个Batched 3D Model (*.b3dm)。目前只有数据标准，没有转换工具。有兴趣一起做么？

**Comment by shrekshao** [comment]
并没有使用经验。不过我全职工作是另一个公司的类似这种gis数据标准。
我愿意关注，但是近期应该会继续完成的自身兴趣项目。。战线已经拉得很长了：）

**Comment by shrekshao** [comment]
@PrincessGod. 突然发现你翻译了greggman的webglfundamental啊。现在出webgl2fundamental了。有兴趣一起翻译吗？

**Comment by shrekshao** [comment]
其实像这种优质内容，感觉可以干投机倒把啊。。虽然万门大学，国内的技能培训什么的，我们很不屑，也完全没有开源精神。。但是他妈的就是市场大啊。。钱都给他们赚了优秀内容生产者却只是开源无私奉献感觉很不服啊。。我觉得这里面有些工作可以做。比如做成ppt骗还在教fixed pipeline opengl的国内大学的钱？有收入回馈greggman这类人等我觉得他们也不会不高兴吧

**Comment by PrincessGod** [comment]
@shrekshao 其实不太明白你说的“投机倒把”是什么意思，但是我肯定是希望更多人能够拥有更优质的教程，毕竟我也是自学的，希望好的学习资源可以得到广泛的传播吧。
对于翻译，其实webgl2fundamentals在我翻译之初就有了，当初选择1是因为我觉得还是从1开始学习，做加法吧。其实2对1也是加法，翻译的话可能大部分是不变的，需要针对性的调整一下可能。
你有什么想法我们可以一起做，翻译的话我也是没问题的，有什么计划可以详谈？我把我的qq或微信发你邮箱吧。
