### ISSUE TITLE
LUT need CLAMP_TO_EDGE?

### ISSUE THREAD

**Issue by sdcarterchen** [shrekshao/minimal-gltf-loader#13]
I saw threre a circle on the model,if change LUT WRAP to CLAMP_TO_EDGE,it  disappeared

**Comment by shrekshao** [comment]
Thanks for the feedback! I think you are right.
However I made the change but seems that the circle is still there. 
Could you provide more details about how you fix it? 

https://github.com/shrekshao/minimal-gltf-loader/blob/master/src/index.js#L281

**Comment by sdcarterchen** [comment]
I think you've fixed it.I mean  if you use REPEAT,a red spot will appear on the model. You can test it.
![11](https://user-images.githubusercontent.com/5809551/33801377-d9d2cece-dd94-11e7-877e-a2dff2324e2a.PNG)

**Comment by sdcarterchen** [comment]
看了其他东西，才知道您是国人啊，...我蹩脚的英语还能看得懂(窃喜)...。

**Comment by shrekshao** [comment]
是这个点啊。。之前没注意到。。我以为是那个白的亮点。。多谢
