### ISSUE TITLE
Virtual City looks like a white dome

### ISSUE THREAD

**Issue by cx20** [shrekshao/minimal-gltf-loader#8]
I tried displaying VC.gltf model with Minimal glTF loader.
However, Virtual City looks like a white dome.
[minimal-gltf-loader + VC.gltf result](https://cdn.rawgit.com/cx20/gltf-test/b9ca4920f86e205a7a66fbc62ede47ac15dd39f6/examples/minimal-gltf-loader/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/29827569-45b06410-8d15-11e7-8d90-f1e2d0e8cb7e.png)

[Three.js +VC.gltf result](https://cdn.rawgit.com/cx20/gltf-test/b9ca4920f86e205a7a66fbc62ede47ac15dd39f6/examples/threejs/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/29827736-c3748e1c-8d15-11e7-86dd-fb251d85d238.png)

**Comment by shrekshao** [comment]
Hi @cx20 ! Thanks for your constant support and patience for testing!
I fixed the issue with the latest HEAD at master. Basically by enabling back face culling.

**Comment by cx20** [comment]
@shrekshao Thank you for fixing. It seems that the problem of culling has been solved. 
It may be another problem, but it seems that the floor etc is displayed in white depending on the angle.

[minimal-gltf-loader + VC.gltf result](https://cdn.rawgit.com/cx20/gltf-test/1b01afc6383aa15d7b798b68018939d96eed36ab/examples/minimal-gltf-loader/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/29887209-a70a1368-8df7-11e7-8d95-f86d527d5f4e.png)

Is the usage of the library incorrect?

**Comment by shrekshao** [comment]
@cx20 
I used to think you set the shaded area to white on purpose. Now you help me realize it's a bug. 
Basically it's blended with the canvas background color. It's because I interpolate the alpha channel in the shader. Get it fixed, great thanks! I wouldn't spot this without your work. This could lead to weird behavior in the future.
You just need to update the shaders for this one (`index.html` in your gltf-test)

**Comment by cx20** [comment]
@shrekshao  Thank you for helping! The mystery was solved and it was refreshing.

[minimal-gltf-loader + VC.gltf result](https://cdn.rawgit.com/cx20/gltf-test/d2a5584172c91e36d3d91d8195f12d3312deace5/examples/minimal-gltf-loader/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/29923250-d87277be-8e93-11e7-8f6d-76ca1dff574e.png)

Issue is closed as the problem has been resolved.
