### ISSUE TITLE
TextureSettingsTest double-sided test failed

### ISSUE THREAD

**Issue by cx20** [shrekshao/minimal-gltf-loader#9]
I tried testing TextureSettingsTest.
However, the double-sided test seems to have failed.

[TextureSettingsTest.gltf result](https://cdn.rawgit.com/cx20/gltf-test/d2a5584172c91e36d3d91d8195f12d3312deace5/examples/minimal-gltf-loader/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/29923669-464a1304-8e95-11e7-9b98-be96d2fecae3.png)

I am looking forward to becoming all green.

**Comment by shrekshao** [comment]
@cx20 should have fixed the issue at the lastest HEAD.
Thanks!

**Comment by cx20** [comment]
@shrekshao It's all green. good job!
![image](https://user-images.githubusercontent.com/1833979/29941140-7dae2402-8ecc-11e7-98b0-ad6166781376.png)
